### ISSUE TITLE
site: o.maxLoaded is not a function

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1169]
Started testing master after updating dex-test to 0.3 and my client hit the following JS console error:

![image](https://user-images.githubusercontent.com/9373513/130991568-b18da9ce-d937-4ce6-b46e-53660d67d844.png)

I had placed a buy order at 0.004 for 1 lot by typing in 0.004, then for a sell order I clicked on the depth chart to get 0.004022 as the sell price and submitted the order.  I'm not certain if the buy was still epoch.

There may have been other clicks. I can't be sure.  Should be reproducible or at least clear from the code how this state can be reached.
