### PR TITLE
Fix max order UI.

### LINKED ISSUE #1169: site: o.maxLoaded is not a function
Started testing master after updating dex-test to 0.3 and my client hit the following JS console error:

image

I had placed a buy order at 0.004 for 1 lot by typing in 0.004, then for a sell order I clicked on the depth chart to get 0.004022 as the sell price and submitted the order.  I'm not certain if the buy was still epoch.

There may have been other clicks. I can't be sure.  Should be reproducible or at least clear from the code how this state can be reached.

### PR DESCRIPTION
**Pull request by martonp**
There were multiple issues with the max order UI. There would be a console
error saying the the maxLoaded function was null. This would happen if there
were two concurrent requests where the one that started first finished last.
Also, if a cached value was input while a another value was being fetched,
the cached result would be overridden by the value being fetched from the
client causing a mismatch between the rate in the input box and the result
on the screen.

Closes #1169.

### CODE REVIEW

**Review by buck54321 — CHANGES_REQUESTED** [review]
Righteous changes, but there's a bug for estimating the **max sell with an empty book** where the loading spinner is not removed.

Screenshot from 2021-08-28 12-19-33

Granted, this won't be encountered often in the wild.

**Comment by martonp** [comment]
@buck54321 Should have been hiding the spinner after errors as well. It should be good now.

**Review by chappjc — APPROVED** [review]
Issue is resolved.

**Review by JoeGruffins — APPROVED** [review]

**Review by buck54321 — APPROVED** [review]
